version: "3"
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - /home/luiz/media-center/media-center-config/plextraktsync:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
