#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'youtube-dl==2019.9.28','console_scripts','youtube-dl'
__requires__ = 'youtube-dl==2019.9.28'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('youtube-dl==2019.9.28', 'console_scripts', 'youtube-dl')()
    )
